### ISSUE TITLE
The firewall stuff

### ISSUE THREAD

**Issue by thesteve0** [jcantrill/jctoolbox#4]
I don't understand when and where we need the firewall rules in the instructions that show up at the end. Does anyone understand when and where those firewall rules are needed

**Comment by jcantrill** [comment]
Are you refering to the following?

```
To make the ha-proxy reachable from the host, you need to add a port forwarding rule from 80 to 1080, which
requires root privilege. Use iptables on linux based:
  sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 1080
```

I stole this from the fabric8 instructions and I believe this is the only way you can make clicking the link in the url return without having to manually modify the port.  I believe I did this before but it hijacks your ability to go to any other sites, but don't quote me on it.  Networking is definitely not my thing.  Maybe @jimmidyson can answer since I based it on his work

**Comment by thesteve0** [comment]
Yeah that is the section I am referring to. How would someone do this on
windows?And if this is really required that seems like a lot of problem for
someone to set up

Thanks
Steve

**Comment by jcantrill** [comment]
I have not attempted any of these instructions on windows and don't know much about windows networksing so I am unable to comment; I have just taken it as a dev experience that I had to manually alter the port for the routes.  This is less then ideal and I imagine(hope) there has to be some way to nat a port for a specific domain.  This case it would be 'vagrant.openshift.dev'.  This is how landrush is handling the dns resolution now I believe.

**Comment by jimmidyson** [comment]
We don't use port forwarding at all work our vagrant setup, just hit the vm ip directly & all is good.

**Comment by jcantrill** [comment]
@thesteve0 removed the portfowarding block as @jimmidyson  told me the source Vagrantfile never had it....im not convinced :)  I have discovered, however, the builder pods dont seem to resolve DNS correctly without a vm restart.
